//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liberty.POC.UI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public long SessionID { get; set; }
        public string ClientName { get; set; }
        public string CurrentStep { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public string Personal { get; set; }
        public bool Completed { get; set; }
    }
}
